### ISSUE TITLE
有点小报错

### ISSUE THREAD

**Issue by godzeo** [Freakboy/CobaltStrike#3]
用的idea 启动有点小报错，不知道怎么解决
设置
![image](https://user-images.githubusercontent.com/64398024/97841814-85bfd500-1d21-11eb-8611-f78f9f8c4408.png)

正常启动后
![image](https://user-images.githubusercontent.com/64398024/97841921-bb64be00-1d21-11eb-93b4-8e8e53fe423d.png)

最终bao报红

![image](https://user-images.githubusercontent.com/64398024/97841685-51e4af80-1d21-11eb-8912-9cf16f9a6ea8.png)

**Comment by Freakboy** [comment]
这是没有copy资源文件,回头有时间我优化一下编译脚本

**Comment by yckyos261** [comment]
土辦法就是 在那個路勁前面加個main就行了。。。這種：main/resources/xxx.icon

**Comment by johnnyxxyy** [comment]
打包好的jar包找不到libs目录和resources目录 里的文件，打包配置文件有问题，对gradle不熟悉不知道怎么修改，坐等答案

**Comment by duraki** [comment]
@yckyos261: 

Good idea. Another way to compile successfully although as a hotfix is to comment these two lines and comment both occurences at `DialogUtils` and `jFrame`. You will lose some graphics in the process but CobaltStrike will successfully compile and connect to remote team server.

**Comment by godzeo** [comment]
上面说的可以解决这个问题
注释掉下面的语句
setIconImage(DialogUtils.getImage("main/resources/armitage-icon.gif"));
jFrame.setIconImage(getImage("main/resources/armitage-icon.gif"));

启动参数：-XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelG

**Comment by r4b3rt** [comment]
#build.gradle

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '4.0.3'
}

task copyResources(type: Copy){
    from 'src/main/resources/armitage-icon.gif'
    into 'build/libs/resources'
}

shadowJar.dependsOn copyResources
shadowJar {
    baseName = 'cs'
    classifier = null
    version = null
    manifest {
        attributes 'Main-Class': 'aggressor.Aggressor'
        attributes 'Implementation-Title': 'cs'
    }
}

gradle shadowJar

cd build/libs

java -XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelGC -jar cs.jar

**Comment by Mimikatz-01** [comment]
where to find this line?
setIconImage(DialogUtils.getImage("main/resources/armitage-icon.gif"));

**Comment by johnnyxxyy** [comment]
Trapped java.lang.NullPointerException during manage user [Manage: neo]: null
java.lang.NullPointerException
	at common.SleevedResource.readResource(SleevedResource.java:16)
	at c2profile.Preview.getPE(Preview.java:55)
	at c2profile.Preview.summarize(Preview.java:44)
	at server.ManageUser.process(ManageUser.java:88)
	at server.ManageUser.run(ManageUser.java:174)
	at java.lang.Thread.run(Thread.java:748)


teamserver show this error, when loading beacon.dll
