### ISSUE TITLE
Failed to excute gradle run

### ISSUE THREAD

**Issue by V0Dien** [Freakboy/CobaltStrike#4]
When I run gradle tasks, it worked perfectly

```
CobaltStrike>gradle tasks

> Task :tasks

------------------------------------------------------------
Tasks runnable from root project
------------------------------------------------------------

Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'cs'.
components - Displays the components produced by root project 'cs'. [incubating]
dependencies - Displays all dependencies declared in root project 'cs'.
dependencyInsight - Displays the insight into a specific dependency in root project 'cs'.
dependentComponents - Displays the dependent components of components in root project 'cs'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'cs'. [incubating]
outgoingVariants - Displays the outgoing variants of root project 'cs'.
projects - Displays the sub-projects of root project 'cs'.
properties - Displays the properties of root project 'cs'.
tasks - Displays the tasks runnable from root project 'cs'.

Verification tasks
------------------
check - Runs all checks.
test - Runs the unit tests.

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradle tasks --all

To see more detail about a task, run gradle help --task <task>

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 960ms
1 actionable task: 1 executed
```
but when I run gradle run to run the project, it failed.

```
CobaltStrike>gradle run

FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'cs'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 637ms
```
Did I do something wrong? I also used IntelliJ IDEA Community Edition 2020.2.3 x64 but got error:

![image](https://user-images.githubusercontent.com/71119588/98894982-9407b100-24d8-11eb-976c-4a0fcb29ce3a.png)

**Comment by Freakboy** [comment]
The error info has been displayed,you should add AggressiveHeap for vm args

**Comment by V0Dien** [comment]
Thank you I added vm args, but It still can not run and same issue with:
https://github.com/Freakboy/CobaltStrike/issues/3
![image](https://user-images.githubusercontent.com/71119588/98920186-5f105400-2502-11eb-9fd1-0ffb08858722.png)

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by de.javasoft.plaf.synthetica.SyntheticaLookAndFeel (file:/C:/
AAA/CobaltStrike-master/libs/synthetica-2.30.0.jar) to method sun.swing.DefaultLookup.setDefaultLookup(sun.swing.DefaultLookup)
WARNING: Please consider reporting this to the maintainers of de.javasoft.plaf.synthetica.SyntheticaLookAndFeel
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Properties.load(Properties.java:407)
	at aggressor.Prefs.load(Prefs.java:43)
	at aggressor.Prefs.getPreferences(Prefs.java:156)
	at aggressor.ui.UseSynthetica.setup(UseSynthetica.java:23)
	at aggressor.Aggressor.main(Aggressor.java:25)
Exception in thread "main" java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1356)
	at dialog.DialogUtils.getImage(DialogUtils.java:580)
	at aggressor.MultiFrame.<init>(MultiFrame.java:126)
	at aggressor.Aggressor.main(Aggressor.java:28)
```

**Comment by Ap3x** [comment]
@V0Dien Did you manage to compile successfully? If so whats the fix?
